apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 
  annotations:
    github.com/project-slug: gennady73/https://github.com/gennady73/rhdh-demo.git
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/rhdh-demo-team"
